# Dependancy https://external-dns.io
# To add a DNS record for wren-ui.myhost.net host
# Note: without authentication, enyone can acess your app, see your data and modify your settings!
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wren-ui-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "360"

spec:
  #instead you may use other ingressClassName such as AWS alb. If other than nginx ingress is used, don't forget to comment unsupported annotations above
  #"nginx" or "alb"
  ingressClassName: nginx
  rules:
    - host: wren.drivex.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wren-ui-svc
                port:
                  number: 3000
### Comment TLS section if you are not going to use https
  tls:
    - hosts:
      - wren.drivex.in
      secretName: wren-drivex-in-tls 
